# shellcheck disable=SC2034
# shellcheck disable=SC2148

export OrchardCore__OrchardCore_AutoSetup__Tenants__0__AdminEmail="";
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__AdminPassword="";
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__AdminUsername="";
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__DatabaseConnectionString="",
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__DatabaseProvider="";
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__DatabaseTablePrefix="";
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__RecipeName="";
export Ozds__Elasticsearch__Client__serverUri="";
export Ozds__Elasticsearch__Client__caPath="";
export Ozds__Elasticsearch__Client__apiKeyId="";
export Ozds__Elasticsearch__Client__apiKey="";
export Ozds__Elasticsearch__Client__user="";
export Ozds__Elasticsearch__Client__password="";
export Ozds__Elasticsearch__External__HelbOzds__Client__connectionString="";
export Ozds__Elasticsearch__External__MyEnergyCommunity__Client__serverUri="";