using OrchardCore.Modules.Manifest;
using Module = OrchardCore.Modules.Manifest.ModuleAttribute;

[assembly: Module(
  Id = "Ozds.Modules.Ozds",
  Name = "Members",
  Dependencies =
    new string[]
    {
      "OrchardCore.Admin",
      "OrchardCore.Diagnostics",
      "OrchardCore.DynamicCache",
      "OrchardCore.Features",
      "OrchardCore.Navigation",
      "OrchardCore.Recipes",
      "OrchardCore.Resources",
      "OrchardCore.Roles",
      "OrchardCore.Settings",
      "OrchardCore.Themes",
      "OrchardCore.Users",
      "OrchardCore.Localization",
      "OrchardCore.Alias",
      "OrchardCore.AdminMenu",
      "OrchardCore.Autoroute",
      "OrchardCore.Html",
      "OrchardCore.ContentFields",
      "OrchardCore.ContentPreview",
      "OrchardCore.Contents",
      "OrchardCore.Contents.FileContentDefinition",
      "OrchardCore.ContentTypes",
      "OrchardCore.CustomSettings",
      "OrchardCore.Deployment",
      "OrchardCore.Deployment.Remote",
      "OrchardCore.Feeds",
      "OrchardCore.Flows",
      "OrchardCore.Indexing",
      "OrchardCore.Layers",
      "OrchardCore.Lucene",
      "OrchardCore.Lists",
      "OrchardCore.Markdown",
      "OrchardCore.Media",
      "OrchardCore.Menu",
      "OrchardCore.Placements",
      "OrchardCore.Queries",
      "OrchardCore.Shortcodes.Templates",
      "OrchardCore.Rules",
      "OrchardCore.Taxonomies",
      "OrchardCore.Title",
      "OrchardCore.Templates",
      "OrchardCore.Users",
      "OrchardCore.Users.Registration",
      "OrchardCore.Users.ResetPassword",
      "OrchardCore.Widgets",
      "OrchardCore.Workflows",
      "OrchardCore.Localization",
      "OrchardCore.ContentLocalization",
      "OrchardCore.ContentLocalization.ContentCulturePicker",
      "OrchardCore.ContentFields.Indexing.SQL.UserPicker",
      "OrchardCore.BackgroundTasks",
      "OrchardCore.Spatial",
      "OrchardCore.Contents.Deployment.Download",
      "Etch.OrchardCore.Fields.Dictionary"
    })]
