#!/usr/bin/env bash

git clean -Xd \
  -e '!.husky/' \
  -e '!.husky/_/' \
  -e '!.husky/_/*' \
  -e '!scripts/' \
  -e '!scripts/.env' \
  -e '!Elasticsearch.Test/' \
  -e '!Elasticsearch.Test/appsettings.json' \
  $@;
