#!/usr/bin/env bash

git clean -Xd \
  -e '!.husky/' \
  -e '!.husky/_/' \
  -e '!.husky/_/*' \
  -e '!Elasticsearch.Test/' \
  -e '!Elasticsearch.Test/secrets.json' \
  -e '!OzdsWeb/' \
  -e '!OzdsWeb/secrets.json' \
  $@;
