#!/usr/bin/env bash

git clean -Xd \
  -e '!.husky/' \
  -e '!.husky/_/' \
  -e '!.husky/_/*' \
  -e '!test/' \
  -e '!test/Ozds.Elasticsearch.Test/' \
  -e '!test/Ozds.Elasticsearch.Test/secrets.json' \
  -e '!src/' \
  -e '!src/Ozds.Web/' \
  -e '!src/Ozds.Web/secrets.json' \
  $@;
