#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")";
ROOT_DIR="$(dirname "$SCRIPT_DIR")";

export ASPNETCORE_ENVIRONMENT=Development;
export DOTNET_ENVIRONMENT=Development;
export ORCHARD_APP_DATA="$ROOT_DIR/App_Data";
export NODE_OPTIONS="--no-warnings";

yarn --cwd "$ROOT_DIR" build;
dotnet run --project "$ROOT_DIR/src/Ozds.Web/Ozds.Web.csproj";
