#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")";

"$SCRIPT_DIR/clean" -f;

stop-watch() {
  if [[ "$1" ]]; then
    kill "$1";
  fi;
}
stop-watch "$THEME_WATCH_PID";
stop-watch "$SOLUTION_WATCH_PID";

"$SCRIPT_DIR/watch-debug";
