#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")";
ROOT_DIR="$(dirname "$SCRIPT_DIR")";

set-project-secrets() {
  if [[ -f "$1/secrets.json" ]]; then
    cat "$1/secrets.json" | \
      dotnet user-secrets set \
        --project "$1/$1.csproj"
  fi;
  echo "Set secrets for project $1";
}

set-project-secrets "$ROOT_DIR/test/Ozds.Elasticsearch.Test"
set-project-secrets "$ROOT_DIR/src/Ozds.Web"
