#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")";
ROOT_DIR="$(dirname "$SCRIPT_DIR")";

set-project-secrets() {
  if [[ -f "$ROOT_DIR/secrets.json" ]]; then
    cat "$ROOT_DIR/secrets.json" | dotnet user-secrets set --project "$1";
  fi;
}

set-project-secrets \
  "$ROOT_DIR/test/Ozds.Elasticsearch.Test/Ozds.Elasticsearch.Test.csproj"

set-project-secrets \
  "$ROOT_DIR/src/Ozds.Web/Ozds.Web.csproj"
