#!/usr/bin/env bash

fd '(.*)?.[0-9]+(.*)?.recipe.json' | xargs rm -f

migration="./OzdsTheme/Migrations/0";
split-recipe \
  "$migration/ozds.orig.recipe.json" \
  "$migration" \
  "$migration/ozds.recipe.json";
split-content-data \
  "$migration/ozds.7.content.recipe.json";

migration="./Members/Migrations/0";
split-recipe \
  "$migration/init.orig.recipe.json" \
  "$migration" \
  "$migration/init.recipe.json";
split-content-data \
  "$migration/init.1.content.recipe.json";
