#!/usr/bin/env bash

main() {
  local recipe_path="$(realpath "$1")";
  [[ -f "$recipe_path" ]] || exit 1;

  local recipe_dir="$(dirname "$recipe_path")";
  local recipe_name="$(basename "$recipe_path")"
  local recipe="$(cat "$recipe_path")";

  local out_dir="$([[ -d "$2" ]] && realpath "$2" || realpath "$recipe_dir")";
  [[ -d "$out_dir" ]] || exit 1;

  local i=0;
  local n=1;

  while :; do
    local data_path=".steps[0].Data[$i]";
    local data="$(echo "$recipe" | jq "getpath(path($data_path))")";
    local type="$(get_type "$data")";

    if [[ $type == "null" ]] || [[ $type == "whitespace" ]]; then
      echo "null";
      break;
    fi;

    local result="$(echo "{
          \"steps\": [
            {
              \"name\": \"content\",
              \"Data\": $data
            }
          ]
        }" | jq)";
    recipe="$(echo "$recipe" | jq "del($data_path)")";

    local content_type="$(echo $data | jq -r "getpath(path(.ContentType))")";
    local name="$( \
      echo "$recipe_name" | \
      sd "(.*)\.recipe\.json" "\$1.$n.$content_type.recipe.json")";
    local path="$out_dir/$name";

    echo "$recipe_dir" "$recipe_name" "$out_dir" "$step_name" "$name" "$path";
    echo "$result" > "$path";

    ((n=$n+1));
  done;

  echo -e "$recipe";
  echo "$recipe" > "$recipe_path";
}

get_type () {
  local whitespace=$(printf '\n\t ');
  local step="$@";

  case "$step" in
    null) echo "null";;
    *[!$whitespace]*) echo "$step";;
    *) echo "whitespace";;
  esac;
};

main $@;
