#!/usr/bin/env bash

main() {
  local recipe_path="$(realpath "$1")";
  [[ -f "$recipe_path" ]] || exit 1;
  local recipe_dir="$(dirname "$recipe_path")";
  local recipe="$(cat "$recipe_path")";

  local out_recipe="$([[ "$3" ]] && realpath "$3" || realpath "$recipe_path")";
  [[ "$out_recipe" ]] || exit 1;

  local out_dir="$([[ -d "$2" ]] && realpath "$2" || realpath "$recipe_dir")";
  [[ -d "$out_dir" ]] || exit 1;

  local recipe_name="$(basename "$out_recipe")"

  local variables_path=".variables";
  local variables="$(echo "$recipe" | jq "getpath(path($variables_path))")";

  local i=0;
  local n=1;
  while :; do
    local step_path=".steps";
    local step="$(echo "$recipe" | jq "getpath(path($step_path[$i]))")";
    local type="$(get_type "$step")";

    if [[ $type == "null" ]] || [[ $type == "whitespace" ]]; then
      echo "null";
      break;
    fi;

    if [[ $type == "feature" ]]; then
      ((i=$i+1));
      echo "[[ $type ]]" $i;

      ((n=$n+1));
      continue;
    fi;

    local result='{}';
    if [[ $variables != "null" ]]; then
      local result="$(echo '{}' | \
          jq "setpath(path($variables_path); $variables)")";
    fi;
    local result="$(echo "$result" | \
        jq "setpath(path($step_path); [$step])")";
    recipe="$(echo "$recipe" | jq "del($step_path[$i])")";

    local step_name="$(echo "$step" | jq -r "getpath(path(.name))")";
    local name="$( \
      echo "$recipe_name" | \
      sd "(.*)\.recipe\.json" "\$1.$n.$step_name.recipe.json")";
    local path="$out_dir/$name";

    echo "$recipe_dir" "$recipe_name" "$out_dir" "$step_name" "$name" "$path";
    echo "$result" > "$path";

    ((n=$n+1));
  done;

  echo -e "$recipe";
  echo "$recipe" > "$out_recipe";
}

get_type () {
  local whitespace=$(printf '\n\t ');
  local step="$@";
  local name="$(echo "$step" | jq -r 'getpath(path(.name))')";

  if [[ "$name" == 'feature' ]]; then
    echo "feature";
    return;
  fi;

  case "$step" in
    null) echo "null";;
    *[!$whitespace]*) echo "$step";;
    *) echo "whitespace";;
  esac;
};

main $@;
