#!/usr/bin/env bash

fd '(.*)?.[0-9]+(.*)?.recipe.json' | xargs rm -f

split-recipe \
  ./OzdsTheme/Recipes/ozds.orig.recipe.json \
  ./OzdsTheme/Migrations/ \
  ./OzdsTheme/Recipes/ozds.recipe.json;

split-content-data \
  ./OzdsTheme/Migrations/ozds.9.content.recipe.json;

split-recipe \
  ./Members/Migrations/init.orig.recipe.json \
  ./Members/Migrations/ \
  ./Members/Migrations/init.recipe.json;

split-content-data \
  ./Members/Migrations/init.2.content.recipe.json;
