#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")";

source "$SCRIPT_DIR/.env";
export ASPNETCORE_ENVIRONMENT=Development;
export DOTNET_ENVIRONMENT=Development;

dotnet watch run --project './OzdsWeb/OzdsWeb.csproj';
