#!/usr/bin/env sh

HUSKY_DIR="$(realpath "$(dirname "$0")")";
ROOT_DIR="$(dirname "$HUSKY_DIR")";
SCRIPTS_DIR="$ROOT_DIR/scripts";

# shellcheck disable=SC1091
. "$HUSKY_DIR/_/husky.sh"

"$SCRIPTS_DIR/format.sh";
"$SCRIPTS_DIR/build.sh";

git add "$ROOT_DIR";
