#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

HUSKY_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")";
ROOT_DIR="$(dirname "$HUSKY_DIR")";

"$ROOT_DIR/scripts/format";
"$ROOT_DIR/scripts/lint";
git add "$ROOT_DIR";
